### ISSUE TITLE
`DEPLOYGATE_MESSAGE` formatting when uploading via gradle plugin. 

### ISSUE THREAD

**Issue by chris-sloan** [DeployGate/gradle-deploygate-plugin#132]
I'm trying to format an upload version message using the `DEPLOYGATE_MESSAGE` environment variable when uploading new builds via the `uploadDeployGateXXXX` gradle task. 

I've tried using `\n`, `\\n` and html `<br>` tags to generate a new line on the package archive list, but I don't seem to be able to obtain the layout I'm after. 

An example String could be `Type: Debug \n Branch: dev \n Message: Pull Request Build for VEA-126. \n Hash: 4f7eeb0`. 

But the output doesn't seem to format as I would expect.

![Screenshot 2022-01-11 at 15 02 09](https://user-images.githubusercontent.com/9352594/148968311-ee2711d1-7e33-4fe7-b38e-2d81917915ae.png)

In a previous iteration of our CI pipeline, we could successfully manage this using `\n`. this was when the message was created through a gradle task, but now I need to obtain some CI environment values for the message too and so can no longer use the gradle task. This previous gradle task would output something like 

![Screenshot 2022-01-11 at 15 11 15](https://user-images.githubusercontent.com/9352594/148968556-a16dfbf6-a466-49be-bfc1-6bba81bf44e4.png)

Is there something I can do to format the output as before?

**Comment by jmatsu** [comment]
We'll investigate this behavior. I think `\n` should be recognized as new lines.

**Comment by jmatsu** [comment]
@chris-sloan 
Could you please check if your `DEPLOYGATE_MESSAGE` correctly handle escape characters? You can check the validness by using `echo`.

incorrect|correct
----|----
![ss 2022-01-13 at 11 36 45](https://user-images.githubusercontent.com/4340693/149255914-39e51ce7-fb5b-4aea-9ef4-f9b435842032.png)|![ss 2022-01-13 at 11 37 26](https://user-images.githubusercontent.com/4340693/149255918-6ec88010-4cbd-4047-8cb7-966c2c749123.png)

`DEPLOYGATE_MESSAGE="$(echo -e "$DEPLOYGATE_MESSAGE")"` will be your help if you have used incorrect value.

**Comment by jmatsu** [comment]
We are going to close this issue because it has been staled. 

@chris-sloan 
Please feel free to re-open this issue if the problem still exists.
