### ISSUE TITLE
uploadDeployGate* doesn't run assemble tasks on Android Gradle plugin 2.2.0-alpha1

### ISSUE THREAD

**Issue by tnj** [DeployGate/gradle-deploygate-plugin#40]
When I run `uploadDeployGateDebug` on a new project using Android Gradle plugin 2.2.0-alpha1, the build fails because there is no APK file exists. Looks like `assembleDebug` isn't triggered. There might be changes on task dependency.

**Comment by tnj** [comment]
https://plus.google.com/+DanBachelderZumper/posts/BkZ96eKpDsP might be related

**Comment by tnj** [comment]
Still exists on alpha2.  Confirmed `output.assemble` was `null` at https://github.com/DeployGate/gradle-deploygate-plugin/blob/master/src/main/groovy/com/deploygate/gradle/plugins/DeployGate.groovy#L69 .

**Comment by henteko** [comment]
This issue was fixed on alpha6 ;)
