### ISSUE TITLE
Using of deprecated methods leads to warnings during build with Android Gradle plugin 3.x

### ISSUE THREAD

**Issue by ok3141** [DeployGate/gradle-deploygate-plugin#50]
I can see warning line during the building process with enabled DeployGate plugin:

```
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
```

This line appears for each build variant.

You can read more in this [SO question](https://stackoverflow.com/q/46984770/1891118)

**Comment by jmatsu** [comment]
Let apologize for the too late reply.  
Thank you for your report. We are gonna investigate it.

**Comment by jmatsu** [comment]
Other plugins like `com.google.gms:google-services` printed the messages though, I couldn't find them and doubtful implementations with ver. 1.1.5.

So let me close this for now.
If you still have the same problem, please feel free to open this. Thanks.
