### ISSUE TITLE
Support multiple deploygate account to upload

### ISSUE THREAD

**Issue by congtuyenvip** [DeployGate/gradle-deploygate-plugin#51]
If support to multiple account upload, it'll be more helpful.
currently I must create different gradle config file on different branch to do this

**Comment by jmatsu** [comment]
@congtuyenvip 
Thank you for using our service!

Could you please explain user story more detail? 
We couldn't imagine usecases that require multiple accounts in a single repository and/or for each branch.

**Comment by congtuyenvip** [comment]
@jmatsu thank for your quick reply
For example:
I have application which id (package name) is : abc.xyz.app
I have different favor or build type with same id - package name
I want create CI job to upload those apk for each favor, build type to deploygate account. But package name - app id is unique for each account. So that I can't upload to one account.
the workaround is that, create different branch which deploygate config is different.

For example: 
- Build type debug with abc.xyz.app on dev branch
deploygate {
  userName = "userA"
  token = "tokenUserA"
apks {
    apv_test{..}
}
}
- Build type prod:  with abc.xyz.app on release branch
deploygate {
  userName = "userA"
  token = "tokenUserA"
apks {
    apv_test{..}
}
}

**Comment by jmatsu** [comment]
@congtuyenvip 
I see!

You have two opitions.

One is supplying configrations via environment variables.
Another is using `distribution` feature.

# Environment variable based configuration

ref: https://github.com/DeployGate/gradle-deploygate-plugin#environment-variables

You don't need to configure our plugin in the gradle file. If you can set different environment variables for each branch, then you can upload apks to different accounts.

# Distribution feature

A *distribution a.k.a shared link* behaves like a static page to distribute a specific version of your app. And also, you can create multiple distributions for a single application id.
Of course, this gradle plugin can update an application version to be distributed via a specific *distrubution*.

## Steps

### Create a distribution

You need to just click a `Add a link for sharing` button. You can see the button in the app detail page.

<img src="https://user-images.githubusercontent.com/4340693/40538862-e8274a5e-604d-11e8-85b8-93e2288a5c7d.jpg" width="400">

*In this image, you can see the button in the lower-right corner.*

By the way, I guess it would be better to change the *distribution* title from `Appearance` tab on the distribution to avoid confusing.

Please create distributions as much as you want by repeating an action above.

### Configure the gradle plugin to update a distribution

Please copy `distribution_key` from a URL of a *distribution* page. 
For example, the distribution_key of `https://deploygate.com/distributions/cca783c7effc8aa8b9d2e1ed2bd5df8c459e91ac` is *cca783c7effc8aa8b9d2e1ed2bd5df8c459e91ac*

You can set a distribution key programatically though, it's the easiest to pass a distribution key as an environment variable or a build argument.

**The example below is passing a distribution key as a build argument.**

Our gradle plugin allows to specify `distributionKey` in apks closure. Please set a distribution key you've copied.

```
deployGate {
  apks {
    ...
    distributionKey = project.getProperty("DISTRIBUTION_KEY")
  }
}
...

# command line
./gradlew app:uploadDeployGateDebug -PDISTRIBUTION_KEY=${distribution key for debug}
```

ref: https://github.com/DeployGate/gradle-deploygate-plugin#module-build-file

**And also, our plugin supports environment variable injection.**

```
DEPLOYGATE_DISTRIBUTION_KEY=${distribution key for debug} ./gradlew app:uploadDeployGateDebug
```

ref: https://github.com/DeployGate/gradle-deploygate-plugin#environment-variables

### Run a task to upload

Just do it!

FYI, the number limitation of distributions depends on pricing plans.
See more detail -> https://deploygate.com/pricing 
(This requires you log out to see all pricing plans. We noticed it just now and we'll fix it ASAP. 🙇)

I hope this will help you.

**Comment by congtuyenvip** [comment]
@jmatsu 
Thank for your  support and detail instruction. Deploygate service is so awesome!, I'll try to  do it as you instructed!
