### ISSUE TITLE
Since 3.2.0 beta, BaseVariantOutput#getName() doesn't return a name which followings our expected format

### ISSUE THREAD

**Issue by jmatsu** [DeployGate/gradle-deploygate-plugin#54]
It seems this has been happening at least since android plugin for gradle 3.2.0-beta01

If the project has `foo` product flavor and `bar` build type, then we are expecting that `BaseVariantOutput#name` should return `fooBar`.
However, the latest AGP version returns `foo-bar` instead.

As a result, `uploadDeployGate${FlavorName}${BuildType}` cannot be found.

**Comment by jmatsu** [comment]
this couldn't be found now... 🤔 that was a phantom

**Comment by tnj** [comment]
Might be related to #46?

**Comment by jmatsu** [comment]
oh...? 🤔 
it happened only on 3.0.x and be degraded now, sorry let me fix it.
