### ISSUE TITLE
uploadDeployGate task fails if `skipAssemble = true` is set without `sourceFile`

### ISSUE THREAD

**Issue by kafumi** [DeployGate/gradle-deploygate-plugin#86]
### Summary

`uploadDeployGate<capitalized VariantName>` task fails with following message if `skipAssemble = true` is set and `sourceFile` is not set in configuration.

```
* What went wrong:
Execution failed for task ':app:uploadDeployGateDebug'.
> An apk file to be upload not specified.
```

### How to reproduce

I created a sample app project to reproduce the issue.
https://github.com/kafumi/deploygate-plugin-upload-issue

Here is example output when I execute `uploadDeployGateDebug` task following `assembleDebug` task.

```
$ ./gradlew assembleDebug

BUILD SUCCESSFUL in 4s
26 actionable tasks: 26 executed

$ ./gradlew uploadDeployGateDebug
> Task :app:uploadDeployGateDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:uploadDeployGateDebug'.
> An apk file to be upload not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
2 actionable tasks: 2 executed
```

Here is the `deploygate` configuraion in `app/build.gradle`.

```groovy
deploygate {
    deployments {
        debug {
            skipAssemble = true
        }
    }
}
```

### Workarounds

- The issue doesn't happen if I set explicitly set `sourceFile` in configuration
  - Sample branch I used to check this workaround: https://github.com/kafumi/deploygate-plugin-upload-issue/tree/explicit-source-file
- The issue doesn't happen if `package<Variant>` task is executed along with `uploadDeployGate<Variant>` task
```
$ ./gradlew assembleDebug

BUILD SUCCESSFUL in 2s
26 actionable tasks: 26 executed

$ ./gradlew packageDebug uploadDeployGateDebug

BUILD SUCCESSFUL in 27s
28 actionable tasks: 2 executed, 26 up-to-date
```

### Notes

- The issue doesn't heppen if I use Gradle DeployGate plugin v1
  - Sample branch with v1 plugin: https://github.com/kafumi/deploygate-plugin-upload-issue/tree/with-v1-plugin

**Comment by jmatsu** [comment]
Thank you for reporting! I could replicate this problem.

Android Gradle Plugin 3.5 skips configuring non-used variants, it's `debug` in this case, because of build performance improvements. So it looks DeployGate plugin cannot find an apk file location because `debug` variant and its properties are not served to our plugin.

**Comment by jmatsu** [comment]
v1 used obsoleted apis and it prevented this issue unexpectedly. 🤷‍♂

**Comment by jmatsu** [comment]
Sorry, let me close this issue after releasing the new version.

**Comment by kafumi** [comment]
Thank you for the swift response and action! I understand. Looking forward to the next release 🙏

**Comment by jmatsu** [comment]
@kafumi 
2.0.2 which includes the fixing has been released.
Thank you for your dedicated research! It helped me a lot~ 🎉

**Comment by nangbanmai1907** [comment]
"The issue doesn't happen if package<Variant> task is executed along with uploadDeployGate<Variant>"

Name `Variant` must be the same
